# Generated by Django 3.1.5 on 2021-04-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
